set nocompatible
filetype off

set encoding=utf-8
set fileencoding=utf-8

scriptencoding utf-8

call plug#begin('~/.vim/plugged')

Plug 'gmarik/vundle'
Plug 'rking/ag.vim'
Plug 'godlygeek/tabular'
Plug 'kien/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'tmhedberg/matchit'
Plug 'vim-scripts/tComment'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-rake'
Plug 'tpope/vim-surround'
Plug 'airblade/vim-gitgutter'
Plug 'vim-ruby/vim-ruby'
Plug 'benmills/vimux'
Plug 'pgr0ss/vimux-ruby-test'
Plug 'itchyny/lightline.vim'
Plug 'fatih/vim-go'
Plug 'mattn/gist-vim'
Plug 'elzr/vim-json'
Plug 'junegunn/vim-easy-align'
Plug 'sdanielf/vim-stdtabs'     " Standard indentation matching language
Plug 'bogado/file-line'         " Open at line
Plug 'mhinz/vim-startify'
Plug 'tpope/vim-eunuch'         " Unix helpers SudoWrite
Plug 'scrooloose/syntastic'
Plug 'ntpeters/vim-better-whitespace'
Plug 'NLKNguyen/papercolor-theme'
Plug 'majutsushi/tagbar'
Plug 'Konfekt/FastFold'
Plug 'romainl/vim-qf'
Plug 'tpope/vim-fugitive'
Plug 'mxw/vim-jsx'
Plug 'pangloss/vim-javascript'
Plug 'elixir-editors/vim-elixir'
Plug 'christoomey/vim-tmux-navigator'


call plug#end()

set nobackup
set nowritebackup
set notimeout
set ttimeout
set ttimeoutlen=10
set noswapfile                    " It's 2012, Vim."
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set t_Co=256
set showmatch           " show matching bracket (briefly jump)
set matchtime=10         " show matching bracket for 1 seconds
set showmode            " show mode in status bar (insert/replace/...)
set matchpairs+=<:>     " specially for html
syntax on

set spelllang=en
set spellfile=$HOME/.vim/spell/en.utf-8.add

" Fix backspace
set backspace=indent,eol,start
fixdel

" Send more characters for redraws
set ttyfast

" Enable mouse use in all modes
set mouse=a
set ttymouse=xterm2

filetype plugin indent on

" Allow cursor after last line character
set virtualedit=onemore

" Automatically reload modified files
set autoread

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent

" Display extra whitespace
set list listchars=tab:»·,trail:·

" Remove white spaces
autocmd BufWritePre * :%s/\s\+$//e

" Clipboard fix for OsX
set clipboard=unnamed

" Numbers
set number
set numberwidth=2

" short lines
set lines=35 columns=150
set colorcolumn=90

" Folding
set foldmethod=indent
set foldlevelstart=99

" Autocompletion options
set wildmode=list:longest,list:full
set complete=.,w,b,u,t

" When spellcheck is enabled, autocomplete from dictionary
set complete+=kspell

" Nerdtree start on open console
" let g:nerdtree_tabs_open_on_console_startup=1

" Silent
set noerrorbells visualbell t_vb=

source $HOME/.vim/go.vim
source $HOME/.vim/spelling.vim
source $HOME/.vim/autocommands.vim
source $HOME/.vim/plugins.vim
source $HOME/.vim/shortcuts.vim
source $HOME/.vim/syntax.vim
source $HOME/.vim/tmux.vim
source $HOME/.vim/visual_fixes.vim

syntax enable
set background=light
silent! colorscheme PaperColor
set cursorline

" Gist
let g:gist_post_private = 1
let g:gist_detect_filetype = 1

" Stupid shift key fixes
com! W w
com! WQ wq
com! Wq wq
com! Q q

" Write the file as sudoer
cmap w!! w !sudo tee % >/dev/null

set guifont=Menlo\ Regular:h18

set wildignore+=*/.hg/*,*/.svn/*,*/vendor/cache/*,*/public/system/*,*/tmp/*,*/log/*,*/.git/*,*/.jhw-cache/*,*/solr/data/*,*/node_modules/*,*/.DS_Store
