set nocompatible
filetype off

set encoding=utf-8
set fileencoding=utf-8

scriptencoding utf-8

" Setup Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()

Plugin 'gmarik/vundle'
Plugin 'rking/ag.vim'
Plugin 'godlygeek/tabular'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'tmhedberg/matchit'
Plugin 'vim-scripts/tComment'
Plugin 'tpope/vim-abolish'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'AndrewRadev/splitjoin.vim'
Plugin 'jiangmiao/auto-pairs'
Plugin 'airblade/vim-gitgutter'

Plugin 'mattn/emmet-vim'
Plugin 'vim-ruby/vim-ruby'
Plugin 'davidoc/taskpaper.vim'
Plugin 'kana/vim-textobj-user'
Plugin 'nelstrom/vim-textobj-rubyblock'
Plugin 'msanders/snipmate.vim'

Plugin 'benmills/vimux'
Plugin 'pgr0ss/vimux-ruby-test'
Plugin 'cloud8421/vimux-cucumber'
Plugin 'jgdavey/vim-turbux'

Plugin 'cloud8421/vim-neatstatus'

Plugin 'altercation/vim-colors-solarized'
Plugin 'fatih/vim-go'
Plugin 'mattn/gist-vim'
Plugin 'elzr/vim-json'
Plugin 'mattn/webapi-vim'
Plugin 'junegunn/vim-easy-align'
Plugin 'sjl/vitality.vim'         " AutoReload
Plugin 'Shougo/neocomplcache.vim' " Autocompletion
Plugin 'sdanielf/vim-stdtabs'     " Standard indentation matching language
Plugin 'bogado/file-line'
Plugin 'mhinz/vim-startify'
Plugin 'tpope/vim-eunuch'

Plugin 'scrooloose/syntastic'

Plugin 'NLKNguyen/papercolor-theme'

call vundle#end()

set nobackup
set nowritebackup
set notimeout
set ttimeout
set ttimeoutlen=10
set noswapfile                    " It's 2012, Vim."
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set t_Co=256
set showmatch           " show matching bracket (briefly jump)
set matchtime=2         " show matching bracket for 0.2 seconds
set showmode            " show mode in status bar (insert/replace/...)
set matchpairs+=<:>     " specially for html
syntax on

set spelllang=en
set spellfile=$HOME/.vim/spell/en.utf-8.add

" Fix backspace
set backspace=indent,eol,start
fixdel

" Send more characters for redraws
set ttyfast

" Enable mouse use in all modes
set mouse=a
set ttymouse=xterm2

filetype plugin indent on

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab

" Display extra whitespace
set list listchars=tab:»·,trail:·

" Remove white spaces
autocmd BufWritePre * :%s/\s\+$//e

" Clipboard fix for OsX
set clipboard=unnamed

" Numbers
set number
set numberwidth=2

" short lines
set lines=35 columns=150
set colorcolumn=90

"Folding
set foldmethod=indent
set foldlevelstart=99

" Autocompletion options
set wildmode=list:longest,list:full
set complete=.,w,b,u,t

" When spellcheck is enabled, autocomplete from dictionary
set complete+=kspell

" Nerdtree start on open console
" let g:nerdtree_tabs_open_on_console_startup=1

" Silent
set noerrorbells visualbell t_vb=

source $HOME/.vim/autocommands.vim
source $HOME/.vim/plugins.vim
source $HOME/.vim/shortcuts.vim
source $HOME/.vim/syntax.vim
source $HOME/.vim/tmux.vim
source $HOME/.vim/visual_fixes.vim

syntax enable
set background=light
silent! colorscheme PaperColor
set cursorline


let g:go_fmt_command = "goimports"

" Gist
let g:gist_post_private = 1
let g:gist_detect_filetype = 1

" Stupid shift key fixes
com! W w
com! WQ wq
com! Wq wq
com! Q q

" Write the file as sudoer
cmap w!! w !sudo tee % >/dev/null

set guifont=Menlo\ Regular:h18

set wildignore+=*/.hg/*,*/.svn/*,*/vendor/cache/*,*/public/system/*,*/tmp/*,*/log/*,*/.git/*,*/.jhw-cache/*,*/solr/data/*,*/node_modules/*,*/.DS_Store
