set nocompatible
filetype off

set encoding=utf-8
scriptencoding utf-8

" Setup Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()

Plugin 'gmarik/vundle'
Plugin 'rking/ag.vim'
Plugin 'godlygeek/tabular'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'tmhedberg/matchit'
Plugin 'vim-scripts/tComment'
Plugin 'tpope/vim-abolish'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'AndrewRadev/splitjoin.vim'
Plugin 'jiangmiao/auto-pairs'
Plugin 'airblade/vim-gitgutter'

Plugin 'mattn/emmet-vim'
Plugin 'vim-ruby/vim-ruby'
Plugin 'davidoc/taskpaper.vim'
Plugin 'kana/vim-textobj-user'
Plugin 'nelstrom/vim-textobj-rubyblock'
Plugin 'msanders/snipmate.vim'

Plugin 'benmills/vimux'
Plugin 'pgr0ss/vimux-ruby-test'
Plugin 'cloud8421/vimux-cucumber'
Plugin 'jgdavey/vim-turbux'

Plugin 'cloud8421/vim-neatstatus'

Plugin 'altercation/vim-colors-solarized'
Plugin 'tomasr/molokai'
Plugin 'fatih/vim-go'
Plugin 'gmarik/sudo-gui.vim'
Plugin 'christoomey/vim-tmux-navigator'

call vundle#end()

set nobackup
set nowritebackup
set notimeout
set ttimeout
set ttimeoutlen=10
set noswapfile                    " It's 2012, Vim."
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set t_Co=256
syntax on

set spelllang=en
set spellfile=$HOME/.vim/spell/en.utf-8.add

" Fix backspace
set backspace=indent,eol,start
fixdel

" Send more characters for redraws
set ttyfast

" Use Bash as shell
set shell=/bin/bash

" Enable mouse use in all modes
set mouse=a
set ttymouse=xterm2

filetype plugin indent on

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab

" Display extra whitespace
set list listchars=tab:»·,trail:·
" Clipboard fix for OsX
set clipboard=unnamed

" Numbers
set number
set numberwidth=2

"Folding
set foldmethod=indent
set foldlevelstart=99

" Autocompletion options
set wildmode=list:longest,list:full
set complete=.,w,b,u,t

" When spellcheck is enabled, autocomplete from dictionary
set complete+=kspell

" Tags
let Tlist_Ctags_Cmd = "/usr/local/bin/ctags -R --exclude=.git --exclude=log -f ./.tags *"
set tags+=.tags

" Tags
let Tlist_Ctags_Cmd = "/usr/local/bin/ctags -R --exclude=.git --exclude=log -f ./.tags *"
set tags+=.tags

" Nerdtree start on open console
" let g:nerdtree_tabs_open_on_console_startup=1

" Silent
set noerrorbells visualbell t_vb=
source $HOME/.vim/autocommands.vim
source $HOME/.vim/plugins.vim
source $HOME/.vim/shortcuts.vim
source $HOME/.vim/syntax.vim
source $HOME/.vim/tmux.vim
source $HOME/.vim/visual_fixes.vim

let g:solarized_termcolors=256
syntax enable
set background=dark
silent! colorscheme solarized

let g:go_fmt_command = "goimports"
